In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
ss = 5000 #size of sample is 5k
trans_amt = np.random.uniform(10,10000,ss)
customer_age = np.random.randint(18,80,ss)
num_prev_trans= np.random.randint(1,50,ss)
loc_mismatch = np.random.choice([0,1],ss)
time_of_day = np.random.randint(0,24,ss)
is_repeat_offender = np.random.choice([0,1],ss,p=[0.9,0.1])
recent_fraud_flag = np.random.choice([0,1],ss,p=[0.8,0.2])

In [3]:
temp = []
for i in range(ss):
    if (trans_amt[i]>5000 and loc_mismatch[i]==1 and time_of_day[i]>20) or is_repeat_offender[i] == 1 or recent_fraud_flag[i] == 1:
        temp.append(1)
    else:
        temp.append(0)
fraud_status = (np.asarray(temp)).reshape(-1,1)

In [4]:
x = np.column_stack([trans_amt,customer_age,num_prev_trans,loc_mismatch,time_of_day,is_repeat_offender,recent_fraud_flag])

In [6]:
x[0:5,]

array([[8.02796178e+03, 5.50000000e+01, 4.40000000e+01, 1.00000000e+00,
        4.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [7.27128904e+03, 3.70000000e+01, 2.20000000e+01, 0.00000000e+00,
        4.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [9.32874930e+03, 4.20000000e+01, 2.90000000e+01, 1.00000000e+00,
        1.30000000e+01, 0.00000000e+00, 0.00000000e+00],
       [8.78304750e+03, 6.30000000e+01, 2.10000000e+01, 0.00000000e+00,
        3.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [5.96484369e+03, 4.60000000e+01, 1.50000000e+01, 1.00000000e+00,
        1.80000000e+01, 0.00000000e+00, 0.00000000e+00]])

In [7]:
x.shape

(5000, 7)

In [6]:
X_train,X_test,y_train,y_test = train_test_split(x,fraud_status,test_size=0.2,random_state=42)

In [24]:
s = StandardScaler()
X_train = s.fit_transform(X_train)
x_test = s.transform(X_test)

In [25]:
X_train[0:5,:4]

array([[ 0.03399955, -0.39650951,  1.26141618,  0.99501244],
       [ 1.46265547, -0.72879165,  0.55175869, -1.00501256],
       [-1.33652901,  1.70794404, -0.29983029,  0.99501244],
       [-0.83024873,  0.04653334, -1.00948777,  0.99501244],
       [ 0.09450907,  0.1019137 ,  0.76465594, -1.00501256]])

In [18]:
x_test[0:5,0:4]

array([[-0.60003941, -1.55949699, -0.65465903, -1.00501256],
       [-1.7075693 , -1.50411664, -0.37079603, -1.00501256],
       [-1.13718386,  1.32028154,  0.33886145, -1.00501256],
       [ 0.06396518,  0.65571727,  0.55175869, -1.00501256],
       [-0.0189542 ,  0.1019137 ,  0.55175869, -1.00501256]])

In [27]:
x_test[0:5,0:4]

array([[ 3.34785324e+03,  2.00000000e+01,  1.60000000e+01,
        -8.53206394e-17],
       [ 1.85883167e+02,  2.10000000e+01,  2.00000000e+01,
        -8.53206394e-17],
       [ 1.81431931e+03,  7.20000000e+01,  3.00000000e+01,
        -8.53206394e-17],
       [ 5.24356971e+03,  6.00000000e+01,  3.30000000e+01,
        -8.53206394e-17],
       [ 5.00683694e+03,  5.00000000e+01,  3.30000000e+01,
        -8.53206394e-17]])

In [29]:
np.random.seed(42)
w1 = np.random.randn(7, 10) * 0.1  # (7, 10)
b1 = np.zeros((1, 10))  # (1, 10) to match hidden layer

w2 = np.random.randn(10, 1) * 0.1  # (10, 1) to map 10 hidden units to 1 output
b2 = np.zeros((1, 1))  # (1, 1)


In [30]:
w1

array([[ 0.04967142, -0.01382643,  0.06476885,  0.15230299, -0.02341534,
        -0.0234137 ,  0.15792128,  0.07674347, -0.04694744,  0.054256  ],
       [-0.04634177, -0.04657298,  0.02419623, -0.19132802, -0.17249178,
        -0.05622875, -0.10128311,  0.03142473, -0.09080241, -0.14123037],
       [ 0.14656488, -0.02257763,  0.00675282, -0.14247482, -0.05443827,
         0.01109226, -0.11509936,  0.0375698 , -0.06006387, -0.02916937],
       [-0.06017066,  0.18522782, -0.00134972, -0.10577109,  0.08225449,
        -0.12208436,  0.02088636, -0.19596701, -0.1328186 ,  0.01968612],
       [ 0.07384666,  0.01713683, -0.01156483, -0.03011037, -0.1478522 ,
        -0.07198442, -0.04606388,  0.10571222,  0.03436183, -0.17630402],
       [ 0.0324084 , -0.03850823, -0.0676922 ,  0.06116763,  0.10309995,
         0.09312801, -0.08392175, -0.03092124,  0.03312634,  0.09755451],
       [-0.04791742, -0.0185659 , -0.1106335 , -0.11962066,  0.08125258,
         0.135624  , -0.00720101,  0.10035329

In [ ]:
def relu(x):
    return np.maximum(0,x)
def relu_derivative(x):
    # if x>0:
    #     return 1
    # else:
    #     return 0
    return (x>0).astype(float)  #x>0 returns a boolean value i.e. True or False , here that is converted into float

In [10]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))
def sigmoid_derivative(z):
    s=sigmoid(z)
    return s*(1-s)

In [11]:
learning_rate = 0.01
epochs = 5000

In [12]:
for i in range (epochs):
    # forward propagation
    z1 = np.dot(X_train,w1)+b1
    a1 = relu(z1)
    z2 = np.dot(a1,w2)+b2
    a2 = sigmoid(z2)

    # loss function
    loss = -np.mean(y_train*np.log(a2) + (1-y_train)*np.log(1-a2))

    # backward propagation
    dz2 = a2-y_train
    dw2 = np.dot(a1.T,dz2)/len(y_train)
    db2 = np.sum(dz2,axis=0,keepdims=True)/len(y_train)
    da1 = np.dot(dz2,w2.T)
    dz1 = da1 * relu_derivative(z1)
    dw1 = np.dot(X_train.T,dz1)/len(y_train)
    db1 = np.sum(dz1,axis=0,keepdims=True)/len(y_train)

    # update weights and biases
    w2 -= learning_rate * dw2
    b2 -= learning_rate * db2
    w1 -= learning_rate * dw1
    b1 -= learning_rate * db1

    # print loss for every 1000 epochs
    if i % 100 == 0:
        print(f"Epoch {i}, Loss: {loss:.4f}")

Epoch 0, Loss: 0.7001
Epoch 100, Loss: 0.6541
Epoch 200, Loss: 0.6205
Epoch 300, Loss: 0.5899
Epoch 400, Loss: 0.5549
Epoch 500, Loss: 0.5090
Epoch 600, Loss: 0.4484
Epoch 700, Loss: 0.3768
Epoch 800, Loss: 0.3055
Epoch 900, Loss: 0.2456
Epoch 1000, Loss: 0.2006
Epoch 1100, Loss: 0.1685
Epoch 1200, Loss: 0.1458
Epoch 1300, Loss: 0.1296
Epoch 1400, Loss: 0.1178
Epoch 1500, Loss: 0.1088
Epoch 1600, Loss: 0.1018
Epoch 1700, Loss: 0.0961
Epoch 1800, Loss: 0.0914
Epoch 1900, Loss: 0.0874
Epoch 2000, Loss: 0.0839
Epoch 2100, Loss: 0.0809
Epoch 2200, Loss: 0.0782
Epoch 2300, Loss: 0.0757
Epoch 2400, Loss: 0.0735
Epoch 2500, Loss: 0.0715
Epoch 2600, Loss: 0.0696
Epoch 2700, Loss: 0.0679
Epoch 2800, Loss: 0.0664
Epoch 2900, Loss: 0.0650
Epoch 3000, Loss: 0.0636
Epoch 3100, Loss: 0.0624
Epoch 3200, Loss: 0.0613
Epoch 3300, Loss: 0.0603
Epoch 3400, Loss: 0.0593
Epoch 3500, Loss: 0.0584
Epoch 3600, Loss: 0.0576
Epoch 3700, Loss: 0.0568
Epoch 3800, Loss: 0.0560
Epoch 3900, Loss: 0.0553
Epoch 4000, 

In [13]:
# Prediction
print("\n Testing results:")
for i in range(len(X_test)):
    z1 = np.dot(X_test[i],w1)+b1
    a1 = relu(z1)
    z2 = np.dot(a1,w2)+b2
    a2 = sigmoid(z2)
print(f"Input: {X_test[i]}, Predicted: {a2[0][0]:.4f}, Actual: {y_test[i][0]}")


 Testing results:
Input: [6.56408815e+03 4.30000000e+01 6.00000000e+00 0.00000000e+00
 3.00000000e+00 0.00000000e+00 1.00000000e+00], Predicted: 1.0000, Actual: 1


In [14]:
# Forward pass on test data
z1_test = np.dot(X_test, w1) + b1
a1_test = relu(z1_test)
z2_test = np.dot(a1_test, w2) + b2
a2_test = sigmoid(z2_test)  # Predicted probabilities

# Convert probabilities to binary predictions (threshold = 0.5)
y_pred = (a2_test >= 0.5).astype(int)

# Calculate accuracy
accuracy = np.mean(y_pred == y_test) * 100
print(f"Test Accuracy: {accuracy:.2f}%")


Test Accuracy: 32.00%
